# Hyperfine beat and (electronic) alignment modelling

From prior work and data:

- Forbes, R. et al. (2018) ‘Quantum-beat photoelectron-imaging spectroscopy of Xe in the VUV’, Physical Review A, 97(6), p. 063417. Available at: https://doi.org/10.1103/PhysRevA.97.063417. arXiv: http://arxiv.org/abs/1803.01081, Authorea (original HTML version): https://doi.org/10.22541/au.156045380.07795038
- Data (OSF): https://osf.io/ds8mk/
- [Quantum Metrology with Photoelectrons (Github repo)](https://github.com/phockett/Quantum-Metrology-with-Photoelectrons), particularly the [Alignment 3 notebook](https://github.com/phockett/Quantum-Metrology-with-Photoelectrons/blob/master/Alignment/Alignment-3.ipynb). Functions from this notebook have been incorporated in the current project, under `qbanalysis.hyperfine`.

## Formalism

In many physical processes, multiple eigenstates of the system are populated. This may be the result of thermal effects, in which case the states are incoherent, or via a coherent preparation process. In the latter case, the overall state of the system can be considered as a wavepacket, and will evolve in time. Assuming that the wavepacket is created “instantaneously” (with respect to the timescale of system/wavepacket evolution), such as via photon-absorption from a short laser pulse, then the ensuing dynamics is simply dependent on the phase-evolution of the eigenstates which form the superposition state.

A textbook example is the preparation of a superposition of hyperfine states in rare gas atoms via photo-absorption. Typically, a small number of hyperfine states are prepared, and their evolution results in relatively simple wavepacket behaviour, exhibiting clear quantum beats, correlated with a changing alignment of the charge distribution. A full treatment can be found in Sect. 4.7 of Blum's book [1].

### Hyperfine quantum beats

For the case of quantum beats from a manifold of (hyperfine) states,
the state multipoles can be expressed as a product of an initial
state, and time-dependent coefficients, as per Eqns. 4.131 and 4.134
in Blum [1]:

\begin{equation}
\langle T(J;t)_{KQ}^{\dagger} \rangle =G(J;t)_{K}\langle T(J)_{KQ}^{\dagger}\rangle
\end{equation}

where the time-dependence is given as:

\begin{equation}
G(J;t)_{K}=\frac{1}{2I+1}\sum_{F',F}(2F'+1)(2F+1)\left\{ \begin{array}{ccc}
J & F' & I\\
F & J & K
\end{array}\right\} ^{2}\cos\left[\frac{(E_{F'}-E_{F})t}{\hbar}\right]
\end{equation}

and $\{...\}$ is a $6j$ symbol, $J$ is the electronic angular momentum,
$I$ the nuclear spin and $F,\,F'$ are hyperfine states that comprise the superposition (wavepacket).

Hence, $\langle T(J)_{KQ}^{\dagger}\rangle$ defines the initial state
of the system after preparation of the state $|J,M\rangle$ (defined by the state multipoles, these are discussed in the following section), and the time-evolution of the superposition
is given by $G(J;t)_{K}$. This contains the angular momentum coupling
between the hyperfine states (defined by the $6j$ symbol), and the
relative phase evolution of the states, expressed in terms of their
energy differences.

### State Multipoles
A more physical picture of the geometric properties of an ensemble can be obtained from the _state multipoles_, which are defined by (spherical) tensor operators. These provide a means to expand the irreducible components of the density matrix, and the geometric properties of the ensemble. (See Chapter 4 in Blum [1] for further details.)

In the $\{|JM\rangle\}$ representation (Eqn. 4.8 in Blum [1]):

\begin{equation}
\hat{T}(J',J)_{KQ}=\sum_{M'M}(-1)^{J'-M'}(2K+1)^{1/2}\left(\begin{array}{ccc}
J' & J & K\\
M' & -M & Q
\end{array}\right)|J'M'\rangle\langle JM|
\end{equation}

Where $\hat{T}(J',J)_{KQ}$ are tensor operators. The corresponding matrix elements are (Eqn. 4.9 in Blum [1]):

\begin{equation}
\langle J'M'|\hat{T}(J',J)_{KQ}|JM\rangle=(-1)^{J'-M'}(2K+1)^{1/2}\left(\begin{array}{ccc}
J' & J & K\\
M' & -M & Q
\end{array}\right)
\end{equation}

The density matrix can be written in terms of the tensor operators
(Eqn. 4.30 in Blum):

\begin{equation}
\boldsymbol{\rho}=\sum_{KQ}\sum_{J'J}\left[\sum_{M'M}\langle J'M'|\hat{\rho}|JM\rangle(-1)^{J'-M'}(2K+1)^{1/2}\left(\begin{array}{ccc}
J' & J & K\\
M' & -M & Q
\end{array}\right)\right]\hat{T}(J',J)_{KQ}
\end{equation}

And the state multipoles are defined as the term in square brackets
(Eqn. 4.31 in Blum):

\begin{equation}
\left\langle T(J',J)_{KQ}^{\dagger}\right\rangle =\sum_{M'M}\langle J'M'|\hat{\rho}|JM\rangle(-1)^{J'-M'}(2K+1)^{1/2}\left(\begin{array}{ccc}
J' & J & K\\
M' & -M & -Q
\end{array}\right)
\end{equation}

And the inverse (Eqn. 4.34 in Blum):

\begin{equation}
\langle J'N'|\hat{\rho}|JN\rangle=\sum_{N'N}(-1)^{J'-N'}(2K+1)^{1/2}\left(\begin{array}{ccc}
J' & J & K\\
N' & -N & -Q
\end{array}\right)\left\langle T(J',J)_{KQ}^{\dagger}\right\rangle 
\end{equation}

The spatial representation of the ensemble can be defined in terms
of the state multipoles - hence the name - by expanding in a suitable
basis, usually the spherical harmonics. For example, for a single
angular momentum state $J$, this is given by (Eqn. 4.101 in Blum):

\begin{equation}
W(\theta,\phi)=\left(\frac{1}{4\pi}\right)^{1/2}\sum_{KQ}(-1)^{J}(2J+1)^{1/2}\left(\begin{array}{ccc}
J & J & K\\
0 & 0 & 0
\end{array}\right)\left\langle T(J)_{KQ}^{\dagger}\right\rangle Y_{KQ}(\theta,\phi)
\end{equation}

Where $W(\theta,\phi)$ is the spatial distribution function, and
$Y_{KQ}(\theta,\phi)$ are spherical harmonics.

### Example: state selected, 1-photon, transition ##
For a basic state-selected transition, following absorption of a photon, 

\begin{equation}
|J_{i}\rangle\overset{1,q}{\rightarrow}|J_{f}\rangle
\end{equation}

The corresponding density matrix is proportional to the angular momentum coupling coefficient (see Sect. 7 in Blum [1]; also Sect. 3.1.1 and Eqn. 3.5 in Hockett [3], and Reid et. al. [4]):

\begin{equation}
\boldsymbol{\rho}^{(1)}(J_f)_{M',M}\propto\sum_{M_{g}}\left(\begin{array}{ccc}
J_{i} & 1 & J_{f}\\
-M_{i} & q & M_{f}
\end{array}\right)^{2}
\end{equation}

Where it has been assumed that the initial state $J_i$ is isotropic, and all $M_i$ are equally populated.

The properties of the final state $M$-level distribution will then depend on the transition ($\Delta J$) and the polarization of the light ($q$).

Note that in the Quantum Beats section the notation was such that $J_i \equiv J'$, and $J_f \equiv J$, and implicitly defined as $\langle T(J;t)_{KQ}^{\dagger} \rangle \equiv \langle T(J'=J\pm1,J;t)_{KQ}^{\dagger} \rangle$, as appropriate for a 1-photon transition.

Hence:

\begin{equation}
\left\langle T(J)_{KQ}^{\dagger}\right\rangle =\sum_{M'M}\boldsymbol{\rho}^{(1)}(J)_{M',M}\times(-1)^{J'-M'}(2K+1)^{1/2}\left(\begin{array}{ccc}
J' & J & K\\
M' & -M & -Q
\end{array}\right)
\end{equation}

**TODO: need to tidy/tighten up notation here. Also distinguish general case from 1-photon and Xe cases herein.**

***
**References**

[1] Blum, K. (2012). Density Matrix Theory and Applications (3rd Editio, Vol. 64). Berlin, Heidelberg: Springer Berlin Heidelberg. https://doi.org/10.1007/978-3-642-20561-3

[2] Zare, R. N. (1988). Angular Momentum: Understanding spatial aspects in chemistry and physics. John Wiley & Sons.

[3] Hockett, P. (2018). Quantum Metrology with Photoelectrons, Volume 1 Foundations. IOP Publishing. https://doi.org/10.1088/978-1-6817-4684-5 (See also links at top of document.)

[4] Forbes, R., Makhija, V., Underwood, J. G., Stolow, A., Wilkinson, I., Hockett, P., & Lausten, R. (2018). Quantum-beat photoelectron-imaging spectroscopy of Xe in the VUV. Physical Review A, 97(6), 063417. https://doi.org/10.1103/PhysRevA.97.063417; also [arXiv 1803.01081](http://arxiv.org/abs/1803.01081); and [web version on authorea](https://www.authorea.com/users/71114/articles/188337-quantum-beat-photoelectron-imaging-spectroscopy-of-xe-in-the-vuv).

[5] Fano, U., & Macek, J. H. (1973). Impact Excitation and Polarization of the Emitted Light. Reviews of Modern Physics, 45(4), 553–573. https://doi.org/10.1103/RevModPhys.45.553

***

## Xe electronic wavepacket dynamics

Here, the wavepacket is modelled, following the [work in ref. [4]](https://www.authorea.com/users/71114/articles/188337-quantum-beat-photoelectron-imaging-spectroscopy-of-xe-in-the-vuv), in which hyperfine wavepackets were prepared in Xe via excitation around 133 nm. Distinct wavepackets are created in the $^{129}Xe$ and $^{131}Xe$ isotopes, which have $I_{129}=1/2$ and $I_{131}=3/2$ and different hyperfine level structures.

For original work see the [Alignment 3 notebook](https://github.com/phockett/Quantum-Metrology-with-Photoelectrons/blob/master/Alignment/Alignment-3.ipynb). This code has been packaged and expanded upon herein (see :py:module:`qbanalysis.hyperfine`), and is used for the calculations below.

Note this version also handles uncertainties in the parameters, via the [uncertainities package](https://pythonhosted.org/uncertainties/index.html), if installed. In this case, [standard linear error propagation](https://en.wikipedia.org/wiki/Propagation_of_uncertainty#Linear_combinations) is applied.

Xe natural abundances ([wiki](https://en.wikipedia.org/wiki/Isotopes_of_xenon#List_of_isotopes)):

- $^{129}Xe$: 0.264006(82) 
- $^{131}Xe$: 0.212324(30)

The relevant energy level structure is given below. The tabulated results are as determined from the experimental work (ref. [4]), see table 1 therein for details and literature values. The figure shows values from NIST.

### Load Xe data

In this case, load the relevant states and properties from file. The parameters are as determined experimentally in ref. [4].

In [1]:
# Load packages
# Main functions used herein from qbanalysis.hyperfine
from qbanalysis.hyperfine import *
import numpy as np
from epsproc.sphCalc import setBLMs

2024-06-13 15:25:54.667 | INFO     | qbanalysis.config:<module>:11 - PROJ_ROOT path is: /home/jovyan/code-share/github-share/Quantum-Beat_Photoelectron-Imaging_Spectroscopy_of_Xe_in_the_VUV
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.


* sparse not found, sparse matrix forms not available. 
* natsort not found, some sorting functions not available. 


* Setting plotter defaults with epsproc.basicPlotters.setPlotters(). Run directly to modify, or change options in local env.


* Set Holoviews with bokeh.
* pyevtk not found, VTK export not available. 
2024-06-13 15:26:00.296 | INFO     | qbanalysis.hyperfine:<module>:28 - Using uncertainties modules, Sympy maths functions will be forced to float outputs.


In [2]:
# Use Pandas and load Xe local data (ODS)
# These values were detemermined from the experimental data as detailed in ref. [4].
from qbanalysis.dataset import loadXeProps
xeProps = loadXeProps()

2024-06-13 15:26:00.416 | INFO     | qbanalysis.dataset:loadXeProps:71 - Loaded Xe data from /home/jovyan/code-share/github-share/Quantum-Beat_Photoelectron-Imaging_Spectroscopy_of_Xe_in_the_VUV/dataLocal/Xe_data_table_fixedFractions.ods.

**Xe measured level splittings and the hyperfine constants.**
Statistical uncertainty estimates are given for the measurements. (See manuscript for details).


A/MHz      B/MHz   Splitting/cm−1
Isotope I   F   F′                                        
129     0.5 0.5 1.5  -5723+/-9  nan+/-nan  0.2863+/-0.0005
131     1.5 1.5 0.5  1697+/-30     -8+/-7  0.0855+/-0.0010
            2.5 1.5  1697+/-30     -8+/-7  0.1411+/-0.0029
                0.5  1697+/-30     -8+/-7  0.2276+/-0.0029

```{figure} Level_Drawing_edit_310518.svg
---
name: Xe-levels-fig
---
Energy-level diagram for the prepared hyperfine states (lower section), and final ion states (upper section). The energies are not to scale. Figure reproduced from ref. [4]. Values from NIST (https://www.physics.nist.gov/PhysRefData/Handbook/Tables/xenontable5.htm).
```

### Model the wavepackets

As noted above, distinct wavepackets are created in the $^{129}Xe$ and $^{131}Xe$ isotopes, which have $I_{129}=1/2$ and $I_{131}=3/2$ and different hyperfine level structures.

In [3]:
# hyperfine.computeModel wraps the necessary computations for both isotopes, including computation of the 1-photon density matrix and hyperfine wavepacket
modelDict = computeModel(xeProps)

# The returned dictionary contains results per isotope:
modelDict.keys()

dict_keys(['129Xe', '131Xe'])

In [4]:
# Plots per isotope
plotOpts = {'width':800}

# Use plotHyperfineModel() to plot results sets, these are returned as Holoviews objects so can also be further modified or laid-out
(plotHyperfineModel(modelDict['129Xe'], **plotOpts) + plotHyperfineModel(modelDict['131Xe'], **plotOpts)).cols(1)

:Layout
   .Overlay.I  :Overlay
      .NdOverlay.I     :NdOverlay   [K,Q]
         :Spread   [t]   (129Xe,129Xe_std)
      .NdOverlay.Model :NdOverlay   [K,Q]
         :Curve   [t]   (129Xe,129Xe_std)
   .Overlay.II :Overlay
      .NdOverlay.I     :NdOverlay   [K,Q]
         :Spread   [t]   (131Xe,131Xe_std)
      .NdOverlay.Model :NdOverlay   [K,Q]
         :Curve   [t]   (131Xe,131Xe_std)

Note here that the error bars are derived from propagation of the input uncertainties. In particular, the temporal evolution is given as Eqn. XX, i.e. $\cos\left[\frac{(E_{F'}-E_{F})t}{\hbar}\right]$. This results in an increasing uncertainty in the model with $t$; this also indicates how a longer measurement window will be more sensitive to the values of the splitting.

For $^{129}Xe$ the dynamics show the expected, simple, quantum beat structure in
the $\langle T(J;t)_{KQ}^{\dagger}\rangle$. For 1-photon excitation,
with linearly polarised light, only $K=0,\,2,\,Q=0$ terms contribute.
The $(0,0)$ term reflects the total population, hence is temporally-invariant,
while the $(2,0)$ term shows the changing alignment as the wavepacket
evolves. 

The allowed terms, and phase of the quantum beats, depends on the transition - i.e. initial and final $J$ state, and photon angular momentum. For example, with circularly polarised light $M_p = +1$, terms with $K=1$ are also allowed, and are out-of-phase with $K=2$ terms.

For $^{131}Xe$, the 3-state system shows more temporal structure in the beat pattern, again dependent on the properties of the intial and final (prepared) states.

### Sum over states

Here the model wavepacket is defined as an incoherent sum over the two isotopic components:

$$
M(t) = 1/n \sum_{i} N_{i}\langle T(J,i;t)_{KQ}^{\dagger} \rangle
$$

Where $i$ labels the isotopes, and $N_{i}$ the natural abundance, and $n=\sum_{i}N_i$ is the normalisation constant.

In [5]:
# 12/06/24 - now working from hyperfine.py WITH UNCERTAINTIES.
# Needs a tidy-up, also checks/tests for values.
modelSum = computeModelSum(modelDict)['sum'] 
plotHyperfineModel(modelSum, **plotOpts)

:Overlay
   .NdOverlay.I     :NdOverlay   [K,Q]
      :Spread   [t]   (sum,sum_std)
   .NdOverlay.Model :NdOverlay   [K,Q]
      :Curve   [t]   (sum,sum_std)

## Quick comparison with experimental data

The experimental data may directly resemble the underlying wavepacket in some cases, e.g. if the probe process is somewhat direct. A quick time-domain plot should reveal similarities, if any...

### Read experimental data

In [6]:
# 

from epsproc import IO
from pathlib import Path

dataPath = Path('/tmp/xe_analysis')
dataTypes = ['BLMall', 'BLMerr', 'BLMerrCycle']   # Read these types, should just do dir scan here.

# # Read from HDF5/NetCDF files
# # TO FIX: this should be identical to loadFinalDataset(dataPath), but gives slightly different plots - possibly complex/real/abs confusion?
# dataDict = {}
# for item in dataTypes:
#     dataDict[item] = IO.readXarray(fileName=f'Xe_dataset_{item}.nc', filePath=dataPath.as_posix()).real
#     dataDict[item].name = item

# Read from raw data files
from qbanalysis.dataset import loadFinalDataset
dataDict = loadFinalDataset(dataPath)

2024-06-13 15:26:02.782 | INFO     | qbanalysis.dataset:loadDataset:244 - Loaded data cpBasex_results_cycleSummed_rot90_quad1_ROI_results_with_FT_NFFT1024_hanningWindow_270717.mat.
2024-06-13 15:26:02.830 | INFO     | qbanalysis.dataset:loadDataset:244 - Loaded data cpBasex_results_allCycles_ROIs_with_FTs_NFFT1024_hanningWindow_270717.mat.
2024-06-13 15:26:03.137 | INFO     | qbanalysis.dataset:loadFinalDataset:220 - Processed data to Xarray OK.


### Plot exp data + model sum

Plot the data as previously, and overlay the wavepacket model (sum case) from above.

Here it is clear that the time-dependence matches reasonaly well in general; the L=4 case (2nd plot) for ROI 0 matches almost exactly, suggesting that there is only a single partial-wave in this case and the ionization is a fairly direct probe in this channel. There is also a slight phase-shift at larger t, which may indicate an issue with the values used for the energy-level splittings here, and/or indicate additional physical processes (e.g. decoherence, multi-electron effects) play a role here in the experimental results. In general, however, modelling of the photoionization dynamics is also required here before any firm conclusions can be made.

TODO: 

- update legends here, should add ROI for expt case.
- update plot titles here, should be L=2, L=4 as per basic data plot, https://phockett.github.io/Quantum-Beat_Photoelectron-Imaging_Spectroscopy_of_Xe_in_the_VUV/0.01_data_download_and_preliminaries_050624.html


In [7]:
from qbanalysis.plots import plotFinalDatasetBLMt
hvData = plotFinalDatasetBLMt(**dataDict)
# hvData

In [21]:
# With functional plotter
# TODO: update legends here, should add ROI for expt case.
# TODO: update plot titles here, should be L=2, L=4 as per basic data plot, https://phockett.github.io/Quantum-Beat_Photoelectron-Imaging_Spectroscopy_of_Xe_in_the_VUV/0.01_data_download_and_preliminaries_050624.html

plotOpts = {'width':1000}
modelPlot = plotHyperfineModel(modelSum, **plotOpts)

# (modelPlot * hvData).opts(width=1000)  # Can't set width here...?
# (modelPlot.opts(width=1000) * hvData.opts(width=1000))  # Ah, this works
# (modelPlot.opts(**plotOpts) * hvData.opts(**plotOpts))  # Ah, this works, although ordering matters...? Must be forced width for some plot/overlay types...?
# modelPlot * hvData

(modelPlot.select(K=2).opts(**plotOpts) * hvData.opts(**plotOpts))
# hvData.opts(**plotOpts) * modelPlot.select(K=2).opts(**plotOpts)

:NdLayout   [l]
   :Overlay
      .NdOverlay.I     :NdOverlay   [K,Q]
         :Spread   [t]   (sum,sum_std)
      .NdOverlay.Model :NdOverlay   [K,Q]
         :Curve   [t]   (sum,sum_std)
      .NdOverlay.II    :NdOverlay   [ROI]
         :Spread   [t]   (BLM per cycle,BLM per cycle_std)
      .NdOverlay.III   :NdOverlay   [ROI]
         :Curve   [t]   (BLM input 0)

INTERESTING....

- L=4 case almost matches exactly... must be direct relation here (if only single partial wave...???). Do see a slight t-shift though, which might be a phase or just expt. shift... TBC...
- Should be sensitive to other stuff for L=2 case?
- Should be sensitive to natural abundances here.
- Safe to assume same matE for isotopes?

Update following uncertainties prop:

- Phase shift here looks real, either shows we can do better in dE extraction here (than pure FT result), and/or there is some additional process going on.
- Fitting to the model should show which is the case. SEE recent UED notebooks for basis-set fitting, although may want to fit directly to model params here...

- **13/06/24 - now working with Uncertainties. Need to add for abundances too...**  Also should add more control over plots, just need to remember how... see https://dev.holoviews.org/user_guide/Applying_Customizations.html#inlining-options, and also need to work on layouts - get some items replaced here.

- **09/06/24 - currently broken for Uncertainties prop case... may want to add switches...?
(v3 in drafts is OK, per current docs.)**

## Versions

In [22]:
import scooby
scooby.Report(additional=['qbanalysis','pemtk','epsproc', 'holoviews', 'hvplot', 'xarray', 'matplotlib', 'bokeh'])

--------------------------------------------------------------------------------
  Date: Thu Jun 13 16:53:20 2024 EDT

                OS : Linux
            CPU(s) : 64
           Machine : x86_64
      Architecture : 64bit
               RAM : 62.8 GiB
       Environment : Jupyter
       File system : btrfs

  Python 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44)
  [GCC 11.3.0]

        qbanalysis : 0.0.1
             pemtk : 0.0.1
           epsproc : 1.3.2-dev
         holoviews : 1.16.2
            hvplot : 0.8.4
            xarray : 2022.3.0
        matplotlib : 3.5.3
             bokeh : 3.1.1
             numpy : 1.23.5
             scipy : 1.10.1
           IPython : 8.13.2
            scooby : 0.7.2
--------------------------------------------------------------------------------

In [23]:
# # Check current Git commit for local ePSproc version
# from pathlib import Path
# !git -C {Path(qbanalysis.__file__).parent} branch
# !git -C {Path(qbanalysis.__file__).parent} log --format="%H" -n 1

In [24]:
# # Check current remote commits
# !git ls-remote --heads https://github.com/phockett/qbanalysis

In [27]:
# Check current Git commit for local code version
import qbanalysis
!git -C {Path(qbanalysis.__file__).parent} branch
!git -C {Path(qbanalysis.__file__).parent} log --format="%H" -n 1

  master
* uncertainties
fc8d83e1673fa0a579e39d31440644ec6c8aa841


In [26]:
# Check current remote commits
!git ls-remote --heads https://github.com/phockett/Quantum-Beat_Photoelectron-Imaging_Spectroscopy_of_Xe_in_the_VUV

88cb8b402641c219854dade2e018687227514eb9	refs/heads/master
fc8d83e1673fa0a579e39d31440644ec6c8aa841	refs/heads/uncertainties
